const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.EightDir,
		C3.Behaviors.scrollto,
		C3.Behaviors.wrap,
		C3.Behaviors.Bullet,
		C3.Behaviors.Timer,
		C3.Behaviors.Pin,
		C3.Behaviors.destroy,
		C3.Plugins.Mouse,
		C3.Behaviors.Orbit,
		C3.Behaviors.Turret,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Behaviors.Turret.Acts.AcquireTarget,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.Mouse.Exps.Y,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.RotateTowardPosition,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Behaviors.EightDir.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Behaviors.Turret.Cnds.OnShoot,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.Count
	];
};
self.C3_JsPropNameTable = [
	{playerHealth: 0},
	{"8Direction": 0},
	{ScrollTo: 0},
	{Wrap: 0},
	{Dash: 0},
	{DashTime: 0},
	{DashCool: 0},
	{TankBottom: 0},
	{Pin: 0},
	{EndCooldown: 0},
	{TankTurret: 0},
	{Bullet: 0},
	{DestroyOutsideLayout: 0},
	{BasicBullet: 0},
	{Mouse: 0},
	{EnemyHealth: 0},
	{MeleeEnemy: 0},
	{Orbit: 0},
	{Turret: 0},
	{RangedEnemy: 0},
	{BombEnemy: 0},
	{EnemyBullet: 0},
	{EnemyShrapnel: 0},
	{CentiHead: 0},
	{ArmorHealth: 0},
	{armor1: 0},
	{segment1: 0},
	{InBetween: 0},
	{CentiTail: 0},
	{BossHealth: 0},
	{ShotTurret: 0},
	{SpreadTurret: 0},
	{HomingTurret: 0},
	{TiledBackground: 0},
	{deadtree: 0},
	{grass1: 0},
	{grass2: 0},
	{grass3: 0},
	{rock1: 0},
	{EnemyBullet2: 0},
	{overlay: 0},
	{Healthbar: 0},
	{Dashbar: 0},
	{PauseButton: 0},
	{segment2: 0},
	{segment3: 0},
	{segment4: 0},
	{segment5: 0},
	{segment6: 0},
	{segment7: 0},
	{armor2: 0},
	{armor3: 0},
	{armor5: 0},
	{armor4: 0},
	{armor6: 0},
	{armor7: 0},
	{armor8: 0},
	{armor9: 0},
	{Sprite15: 0},
	{Sprite16: 0},
	{Sprite17: 0},
	{Sprite18: 0},
	{Sprite19: 0},
	{Sprite20: 0},
	{InBetween2: 0},
	{InBetween3: 0},
	{InBetween4: 0},
	{InBetween5: 0},
	{InBetween6: 0},
	{InBetween7: 0},
	{InBetween8: 0},
	{Flash: 0},
	{hit: 0},
	{BasicEnemies: 0},
	{Environment: 0},
	{CentiBoss: 0},
	{EnemyProjectile: 0},
	{Turret2: 0},
	{Turrets: 0},
	{bossarmor: 0},
	{PlayerCooldown: 0},
	{DashCooldown: 0},
	{Enemies: 0}
];

self.InstanceType = {
	TankBottom: class extends self.ISpriteInstance {},
	TankTurret: class extends self.ISpriteInstance {},
	BasicBullet: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	MeleeEnemy: class extends self.ISpriteInstance {},
	RangedEnemy: class extends self.ISpriteInstance {},
	BombEnemy: class extends self.ISpriteInstance {},
	EnemyBullet: class extends self.ISpriteInstance {},
	EnemyShrapnel: class extends self.ISpriteInstance {},
	CentiHead: class extends self.ISpriteInstance {},
	armor1: class extends self.ISpriteInstance {},
	segment1: class extends self.ISpriteInstance {},
	InBetween: class extends self.ISpriteInstance {},
	CentiTail: class extends self.ISpriteInstance {},
	ShotTurret: class extends self.ISpriteInstance {},
	SpreadTurret: class extends self.ISpriteInstance {},
	HomingTurret: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	deadtree: class extends self.ISpriteInstance {},
	grass1: class extends self.ISpriteInstance {},
	grass2: class extends self.ISpriteInstance {},
	grass3: class extends self.ISpriteInstance {},
	rock1: class extends self.ISpriteInstance {},
	EnemyBullet2: class extends self.ISpriteInstance {},
	overlay: class extends self.ISpriteInstance {},
	Healthbar: class extends self.ISpriteInstance {},
	Dashbar: class extends self.ISpriteInstance {},
	PauseButton: class extends self.ISpriteInstance {},
	Bullet: class extends self.IInstance {},
	segment2: class extends self.ISpriteInstance {},
	segment3: class extends self.ISpriteInstance {},
	segment4: class extends self.ISpriteInstance {},
	segment5: class extends self.ISpriteInstance {},
	segment6: class extends self.ISpriteInstance {},
	segment7: class extends self.ISpriteInstance {},
	armor2: class extends self.ISpriteInstance {},
	armor3: class extends self.ISpriteInstance {},
	armor5: class extends self.ISpriteInstance {},
	armor4: class extends self.ISpriteInstance {},
	armor6: class extends self.ISpriteInstance {},
	armor7: class extends self.ISpriteInstance {},
	armor8: class extends self.ISpriteInstance {},
	armor9: class extends self.ISpriteInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	Sprite16: class extends self.ISpriteInstance {},
	Sprite17: class extends self.ISpriteInstance {},
	Sprite18: class extends self.ISpriteInstance {},
	Sprite19: class extends self.ISpriteInstance {},
	Sprite20: class extends self.ISpriteInstance {},
	InBetween2: class extends self.ISpriteInstance {},
	InBetween3: class extends self.ISpriteInstance {},
	InBetween4: class extends self.ISpriteInstance {},
	InBetween5: class extends self.ISpriteInstance {},
	InBetween6: class extends self.ISpriteInstance {},
	InBetween7: class extends self.ISpriteInstance {},
	InBetween8: class extends self.ISpriteInstance {},
	hit: class extends self.ISpriteInstance {},
	BasicEnemies: class extends self.ISpriteInstance {},
	Environment: class extends self.ISpriteInstance {},
	CentiBoss: class extends self.ISpriteInstance {},
	EnemyProjectile: class extends self.ISpriteInstance {},
	Turrets: class extends self.ISpriteInstance {},
	bossarmor: class extends self.ISpriteInstance {}
}